### ISSUE TITLE
Collection record extent does not match number of published objects

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damspas#492] opened 2018-07-17 20:24 UTC
### Descriptive summary

If a user is in public view mode (not logged in as a curator) and if some collection objects are set to curator-only visibility, the collection record extent does not match the actual number of objects visible in the browse screen.

An example is Stuart Collection Photographs which has a lot of curator-only objects
https://library.ucsd.edu/dc/collection/bb9421444x

![image](https://user-images.githubusercontent.com/5453716/42843237-5563c95e-89c4-11e8-9f98-9a9bf955b573.png)

![image](https://user-images.githubusercontent.com/5453716/42843263-68a9a132-89c4-11e8-8b3b-e7e8e3889a0b.png)

### Expected behavior

The collection record extent should match the number of objects listed in the collection browse mode based on login type.

### Actual behavior

The collection record extent equals the total number of objects, not the number of object visible to the user.

**Comment by mcritchlow** [comment] 2018-07-17 20:41
@GregReser - Makes sense, though I suppose I have 2 comments/questions in response that this ticket raises for me.

1) It seems like both things are potentially valuable to display. Since the current extent could be an indication that there's more a user might ask about and is an actual total. Should it be one over the other? Or is one more valuable? I'm honestly curious, I have no idea.

2) Does "Extent" actually mean anything to a user? Whether we change the value to be dynamic, or show both, Extent seems like a technical term that might be lost on most.

**Comment by lsitu** [comment] 2018-07-17 21:19
Good questions! @mcritchlow 
@GregReser I just want to provide some background regarding how the Extent note in the collection. As you noticed in damspas, it's not the number of objects for a specific view but rather the total number of objects in a collection.
Currently we haven't stored the Extent note in the triplestore and it will be inserted when the metadata (RDF/XML) is requested through damsrepo api (for the example above the url is http://lib-hydratail-prod:8080/dams/api/objects/bb9421444x). The extend note will be indexed to SOLR for UI display when the collection CLR is updated for damspas UI display, and it won't change until the collection CLR is updated, so it might be outdated when more and more objects added to the collection overtime as well.

**Comment by GregReser** [comment] 2018-07-17 21:52
@mcritchlow these are very good questions.  So good that I don't have answers.  I'll have to ask the DMP's group.  Here are some initial thoughts.

1. The number actually visible to the user would be preferred over the full total.  Showing the full total depends on whether or not we would ever let users have access to the curator-only objects (why are they curator-only in the first place?  How would they get access?).  In the case of Stuart Collection, those objects are hidden until the photographer give us rights to publish them, so we might not allow anyone to see them (it's a long story).

2. "Extent" might be mysterious to users.  DMP'S could weigh in on that.

**Comment by GregReser** [comment] 2018-07-17 21:53
@lsitu could we also use the DAMS Manager collection release tool to trigger a re-indexing, even if the CLR is not updated?

**Comment by gamontoya** [comment] 2018-07-17 21:58
@GregReser I think it's a good idea that this be taken to DMPS for feedback so no action should be taken on this ticket at this time.

**Comment by GregReser** [comment] 2018-07-17 22:00
@gamontoya OK

**Comment by hjsyoo** [comment] 2018-07-17 22:07
One option could be not to display Extent at all, unless it's useful for troubleshooting. But again, this may not be of any help to the user.

**Comment by lsitu** [comment] 2018-07-17 22:17
@GregReser Yes, I think we've done that in the collection release tool and the collection CLR will be updated and/or re-indexed. I think this could happen when objects are added to a collection that is already released. Could you open a ticket so that we can work on it? Thanks.

**Comment by GregReser** [comment] 2018-07-17 22:31
@lsitu how about if I test the current CLR release tool to see if it will update the extent in @hjsyoo example https://library.ucsd.edu/dc/collection/bb96275693

**Comment by GregReser** [comment] 2018-07-17 22:33
DMP'S discussion: 
Collection record extent display #83

**Comment by lsitu** [comment] 2018-07-17 22:42
@GregReser It sounds good to test the current CLR release tool to see how it goes. Thanks. BTW, the link you provided above for `Collection record extent display #83` is not correct.

**Comment by GregReser** [comment] 2018-07-18 15:55
@lsitu I confirmed that DAMS Manager collection release does re-index an already released CLR and the extent is updated.  I opened a new ticket to automate re-indexing when objects are added to a collection via Excel ingest. 
https://github.com/ucsdlib/damspas/issues/493

**Comment by gamontoya** [comment] 2018-07-18 20:31
@GregReser Yes, this can be closed. I confirmed with Roger that we will fix the bug but we will not update D4 code to make the extent match the number of objects listed in the collection browse mode based on login type.

**Closed** 2018-07-18 20:38 UTC
Labels: enhancement
