### ISSUE TITLE
Fix access controls for downloading mp3 and mp4 files

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#467] opened 2018-06-20 18:54 UTC
### Descriptive summary

Users are able to download mp3 or mp4 files if they know the full URL path.

- /_2.mp3
- /_2.mp3?download

Objects (any type of content file) that are UCSD-only access should also have Public metadata-only access
- License\permission\Permission\type = "localDisplay"
- OtherRights\permission\Permission\type = "localDisplay"

### Expected behavior

Update access controls for downloading of both mp3, mp4, others?

UCSD IP users should see the content, public users should see the "Restricted content" image instead of content

**Comment by mcritchlow** [comment] 2018-06-20 19:10
I'm curious about this, as it related to work I'm doing with @jhriv  on serving files differently.

Is the issue that _any_ mp3 or mp4 can be downloaded by someone if they know the URL? Or that mp3's that are, say, curator only , can be downloaded by a non-curator? I'm curious what the context is that's currently incorrect.

**Comment by lsitu** [comment] 2018-06-20 20:05
@mcritchlow Good question! I think the context is that though we do not allow the audio/video viewer to have a download button but if someone know about the full url path, they could still be able to download the audio/video. It looks like it's something related to ticket [Remove download function for UCSD-only video objects](https://github.com/ucsdlib/damspas/issues/461), in which one could still be able to download the video even though the download button is removed.
@gamontoya Is it just related to those UCSD-only objects as what's specified in ticket https://github.com/ucsdlib/damspas/issues/461, or all public downloads of audios/videos?

**Comment by mcritchlow** [comment] 2018-06-20 20:13
@lsitu I see, thanks. I do see that there is no download button for mp3's, but there [is for mp4's](https://library.ucsd.edu/dc/object/bb2118519t). This seems odd to me, at the very least inconsistent.. Why can't people download mp3s when they're allowed to stream them, if they're derivatives? (question for @gamontoya )

I suppose my more concrete concern/issue, is that I want to make sure whatever access control checks necessary are performed before [`send_file` is called.](https://github.com/ucsdlib/damspas/blob/send-file/app/controllers/file_controller.rb#L65) Because per @jhriv and my testing so far, nginx and send_file will respect this and not allow direct queries to the URL's @gamontoya posted above, unless the access control checks allow them to.

**Comment by gamontoya** [comment] 2018-06-20 20:41
@GregReser @remerjohnson I'm adding Greg and Ryan to this discussion because they were in the meeting with me AND because they may have use cases that I may not be aware of.

**Comment by GregReser** [comment] 2018-06-20 21:01
@mcritchlow It is odd that all audio downloads are blocked but not all videos.  I think that there was a policy decision to not allow download of any audio file at any access level.  I wasn't involved with that, so we would need confirmation.  For video, we have some collections that seem like they would be OK for public download: Travelogue, Hansen, Insite, Stuart, and several in RDCP.  We have a CC licensed video that seems to me should downloadable (bb76807535) 

There are cases where we don't want to allow any downloads, such as CARS licensed videos that prompted ticket #461.  Our license specifies that no downloads are allowed, either for the public or for UCSD IP addresses.

**Comment by mcritchlow** [comment] 2018-06-20 21:17
@GregReser - Thanks, very interesting. A global policy like that for mp3s seems a bit odd to me if it doesn't also apply to videos since they're both file formats we stream.. It makes me wonder if that was just based on the mp3 content we had at the time, as opposed to an overarching policy.

Either way, as you said, maybe clarifying the policy on both formats, since they're both streamed, would help.

The current code essentially says if you can see the Solr record/show page, you can download a derivative. Master files are blocked to curators. So if there needs to be more nuance/granularity there we'll need to know what metadata to check to decide whether a file is downloadable. Which is sounds like you're saying would be called out by either of these? Is that true for all files?

```
OtherRights\permission\Permission\type = "localDisplay"
License\permission\Permission\type = "localDisplay"
```

**Comment by gamontoya** [comment] 2018-06-20 21:51
Okay @GregReser. Seems like your last paragraph is key. No downloading of licensed media, audio or video.

**Comment by gamontoya** [comment] 2018-06-20 21:55
Example of public object, but no download button:

- https://library.ucsd.edu/dc/object/bb05490835

**Comment by GregReser** [comment] 2018-06-20 22:18
@mcritchlow now I wish we had a predicate for allowDownload.  I think it's a safe compromise to say UCSD-only files cannot be downloaded.

So it's true that these = no download:
`OtherRights\permission\Permission\type = "localDisplay"`
`License\permission\Permission\type = "localDisplay"`

**Comment by lsitu** [comment] 2018-06-20 22:45
@GregReser I think we allow to view/download images (derivatives) on campus with `localDisplay`, but just disallow audio/video files download. Is it correct? 
Will these `localDisplay` objects allow public metadata-only access or not?

**Comment by GregReser** [comment] 2018-06-20 22:54
@lsitu Yes, we allow view/download images (derivatives) on campus with localDisplay, but just disallow audio/video files download.
Let me check on localDisplay objects allow public metadata-only access

**Comment by GregReser** [comment] 2018-06-21 15:59
@lsitu Speaking with DOMM and looking at existing documentation:
[DAMS 4 Access Control Implementation](https://lisn.ucsd.edu/display/dlpg/DAMS+4+Access+Control+Implementation#DAMS4AccessControlImplementation-ProductionIngestProposalProductionIngestProposal)
[Rights Metadata and Policy Matrix](https://lisn.ucsd.edu/display/DCPTF/Rights+Metadata+and+Policy+Matrix)

Yes, localDisplay objects allow public metadata-only access

The logic should be:

otherRights/Permission/type

- metadataDisplay = Public, Boilerplate "Restricted content" displayed instead of content
- localDisplay = UCSD IP only, Display content, audio, video download not allowed


I ran some tests using DAMS Manager to see what access restriction predicates and values are currently created on ingest:
https://docs.google.com/document/d/1OewxCBjvhMKTvKMhv8cr7pPmxmMrXtWFWhN7x1lnuME/edit?usp=sharing

**Comment by lsitu** [comment] 2018-06-21 18:07
@GregReser Thank you very much for clarifying it. It sounds good and I think this is inline with the current implementation for access control that allows public discovery (metadata-only) and UCSD local only read access for `localDisplay` objects. But it seems like that the object viewer/UI may need update for objects like https://librarytest.ucsd.edu/dc/object/bd66071852 in ticket https://github.com/ucsdlib/damspas/issues/461. I can view the video without VPN off campus, which should be public metadata-only placeholder with no download button. 

Do we have a ticket to update the object viewer/UI for `localDisplay` objects (`License\permission\Permission\type = "localDisplay"`, `OtherRights\permission\Permission\type = "localDisplay"`) to support public metadata-only access?

**Comment by GregReser** [comment] 2018-06-21 19:09
I think localDisplay + public metadata-only access will be addressed in #466.  It is specified in the expected behavior

**Comment by lsitu** [comment] 2018-06-21 19:55
@GregReser It looks like the spec in ticket https://github.com/ucsdlib/damspas/issues/466 is for UCSD IP/metadata-only (`metadataDisplay`) collections. I think we had better update the spec of the ticket to include `localDisplay` objects.

**Comment by GregReser** [comment] 2018-06-21 20:18
@gamontoya what do you think, update #466 deal with all localDisplay objects or make a separate ticket?

**Comment by gamontoya** [comment] 2018-06-21 20:19
@GregReser Add it to this ticket.

**Comment by GregReser** [comment] 2018-06-21 21:37
@gamontoya I added the localDisplay = public metadata-only access to the description in this ticket

**Closed** 2018-06-29 19:13 UTC
Labels: dams 4.0
