### ISSUE TITLE
ensure subscripts and superscripts display in collection and object page title

### ISSUE THREAD

**Issue by hannahbegley** [ucsdlib/damspas#348] opened 2017-09-20 17:31 UTC
"sub" and "sup" tags display in DAMS properly in the following places:
object page description (https://librarytest.ucsd.edu/dc/object/bd9812384c)
collection page description (https://librarytest.ucsd.edu/dc/collection/bd68430724)
title in search results (https://librarytest.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Center+for+Aerosol+Impacts+on+Chemistry+of+the+Environment&id=bd5034217p)

They do not display properly in titles on collection or object pages (https://librarytest.ucsd.edu/dc/object/bd91298321)
I confirmed this impacts CLRs too by updating a collection page title to include a subscript.

Super/Subscripts do display in the data view https://librarytest.ucsd.edu/dc/collection/bd91298321/data

**Comment by VivianChu** [comment] 2017-09-29 19:41
@hannahbegley - The problem is fixed in development environment.  I'll let you know when the change get deploy to staging to test. Here are the screen shot.
Before update
![beforetitlesubscript](https://user-images.githubusercontent.com/1864660/31033050-82c1c66c-a513-11e7-8f18-35901b91ddbe.png)

After update
![aftertitlesubscript](https://user-images.githubusercontent.com/1864660/31033060-8fa44986-a513-11e7-9909-7570bf4e0ce5.png)

**Comment by hjsyoo** [comment] 2017-09-29 21:22
@VivianChu @mcritchlow @gamontoya We're trying to decide whether to ingest this collection to prod today or wait until early next week. When do you think this fix will be deployed to prod?

**Comment by mcritchlow** [comment] 2017-09-29 22:03
@hjsyoo - @VivianChu has a fix in that is being reviewed now. I suspect it will get merged today, so deployment is likely going to be early-mid next week depending on the review cycle in staging and deployment w/ OPS

**Comment by hjsyoo** [comment] 2017-09-29 22:24
@mcritchlow Thanks. I think we'll go ahead and ingest as is, so there's no time issue for deploying this fix.

**Closed** 2017-10-02 14:23 UTC
Labels: enhancement

**Comment by VivianChu** [comment] 2017-10-05 17:06
@hannahbegley @hjsyoo - The fix has been deployed to production this morning.

**Comment by hjsyoo** [comment] 2017-10-05 20:44
Thanks @VivianChu! @remerjohnson, I think this means the title edits for CAICE can be implemented.
